sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sachinpandey7/docker-test -f Dockerfile.dev .
  
script:
  - docker run -e CI=true sachinpandey7/docker-test npm run test
  
deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: docker-travis-ci
  env: DockerTravisCi-env
  bucket_name: elasticbeanstalk-ap-south-1-238242600829
  bucket_path: docker-travis-ci
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  