sudo: required
services:
  - docker

before install:
  - docker build -t sachinpandey7/dockerTest -f Dockerfile.dev .
script:
  - docker run -e CI=true sachinpandey7/dockerTest npm run test -- --coverage