sudo: required

services:
  - docker

  before_install:
    - docker build -t sachinpandey7/docker-test -f Dockerfile.dev .
  
  script:
    - docker run -e CI=true sachinpandey7/docker-test npm run test
  